print("helloworld")

In [1]:
print("hello world")

hello world


In [2]:
import numpy as np

In [5]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [6]:
a.reshape(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [7]:
a.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [9]:
np.zeros(4)

array([0., 0., 0., 0.])

In [11]:
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [12]:
np.ones((3,4)) 

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
np.ones((3,4)) * 5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [14]:
np.empty((4,5))

array([[6.23042070e-307, 1.86918699e-306, 1.69121096e-306,
        1.20161118e-306, 8.45549797e-307],
       [1.42417900e-306, 1.78019082e-306, 1.37961913e-306,
        6.23057349e-307, 1.02360935e-306],
       [1.69120416e-306, 1.78022342e-306, 6.23058028e-307,
        1.06811422e-306, 1.22383391e-307],
       [8.01097889e-307, 1.78021663e-306, 1.24610859e-306,
        1.78020848e-306, 2.56765117e-312]])

In [15]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [18]:
import numpy as np

In [21]:
np.linspace(1,5,9)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [22]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [24]:
b = a.reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [25]:
np.sum(b)

66

In [26]:
np.sum(a)

66

In [28]:
np.sum(b,axis=0)

array([12, 15, 18, 21])

In [29]:
np.sum(b,axis=1)

array([ 6, 22, 38])

In [30]:
np.max(b,axis=0)

array([ 8,  9, 10, 11])

In [31]:
np.max(b,axis=1)

array([ 3,  7, 11])

In [32]:
np.min(b,axis=0)

array([0, 1, 2, 3])

In [34]:
np.mean(b,axis=0)

array([4., 5., 6., 7.])

In [35]:
np.median(b,axis=1)

array([1.5, 5.5, 9.5])

In [36]:
np.mode(b)

AttributeError: module 'numpy' has no attribute 'mode'

In [37]:
np.std(a)

3.452052529534663

In [38]:
np .std(b,axis=1)

array([1.11803399, 1.11803399, 1.11803399])

In [39]:
np .random.rand(4)

array([0.27659752, 0.10357763, 0.64191421, 0.56882478])

In [40]:
np.random.rand(3,4)

array([[0.28113703, 0.49924627, 0.44232842, 0.53329785],
       [0.32786029, 0.65284317, 0.93100035, 0.86157339],
       [0.79650676, 0.99811996, 0.85923833, 0.27018753]])

In [41]:
np.random.randint(50,60,5)

array([57, 59, 51, 50, 55])

In [42]:
np.random.seed(10)

In [43]:
np.random.rand(3)

array([0.77132064, 0.02075195, 0.63364823])

In [44]:
np.random.seed(10)
np.random.rand(3)

array([0.77132064, 0.02075195, 0.63364823])

In [46]:
mu = 100
sigma = 15
s = np.random.normal(mu,sigma,100)
s

array([ 83.84672307, 104.50409199, 107.54535666,  83.56631273,
        77.18288393, 103.54152867, 110.45722093,  97.06298085,
       101.79837112, 111.45993082,  95.01019266, 100.3442579 ,
       100.83150843, 105.44136972, 104.4527657 , 121.1043089 ,
       103.31323388, 114.84871552,  88.42899612, 106.87576716,
       126.45438024,  90.23781159,  97.85971735,  85.98842896,
       100.39849709,  80.93931217, 104.44309585, 120.47150102,
        80.43586284, 105.79004535,  73.61522406,  91.74161397,
       124.5793836 ,  95.29269379,  68.69626219, 115.61159866,
       104.95638879,  95.13642216, 120.26433243, 107.09979959,
       104.80895062, 116.24578424, 108.05885049, 119.57047374,
        97.51323815,  80.58115822,  58.62085393, 133.98227122,
        95.20796106, 105.07497126,  95.56821151, 124.83651696,
        85.55037797,  96.86699957,  89.70705366,  95.90353013,
        93.92395463, 103.10085816, 105.16405976,  79.41761992,
       114.69191502,  80.54920294,  91.74029853, 116.85

In [47]:
np.std(s)

14.65788559213187

In [48]:
np.mean(s)

101.00704374821721

In [50]:
d = np.random.rand(12).reshape(3,4)
d

array([[0.28825314, 0.27479513, 0.60105189, 0.9385142 ],
       [0.70729631, 0.26340316, 0.12233592, 0.45872423],
       [0.9748125 , 0.68057437, 0.19325373, 0.04673923]])

In [58]:
d.sort()

In [61]:
d.flatten()

array([0.04673923, 0.19325373, 0.45872423, 0.70729631, 0.12233592,
       0.26340316, 0.60105189, 0.9385142 , 0.27479513, 0.28825314,
       0.68057437, 0.9748125 ])

In [62]:
d

array([[0.04673923, 0.19325373, 0.45872423, 0.70729631],
       [0.12233592, 0.26340316, 0.60105189, 0.9385142 ],
       [0.27479513, 0.28825314, 0.68057437, 0.9748125 ]])

In [63]:
d = d.flatten()
d

array([0.04673923, 0.19325373, 0.45872423, 0.70729631, 0.12233592,
       0.26340316, 0.60105189, 0.9385142 , 0.27479513, 0.28825314,
       0.68057437, 0.9748125 ])

In [64]:
d.sort()

In [65]:
d

array([0.04673923, 0.12233592, 0.19325373, 0.26340316, 0.27479513,
       0.28825314, 0.45872423, 0.60105189, 0.68057437, 0.70729631,
       0.9385142 , 0.9748125 ])

In [66]:
d = d.reshape(3,4)
d

array([[0.04673923, 0.12233592, 0.19325373, 0.26340316],
       [0.27479513, 0.28825314, 0.45872423, 0.60105189],
       [0.68057437, 0.70729631, 0.9385142 , 0.9748125 ]])