In [1]:
import numpy as np

In [2]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [4]:
b = np.array((1,2,3))
b

array([1, 2, 3])

In [6]:
np.arange(12).reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [8]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [10]:
c = np.arange(24).reshape(2,3,4)
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [11]:
c[1,1,1]

17

In [12]:
c[1,2,3]

23

In [13]:
c[1::] #this will show the whole array

array([[[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [14]:
c[0,:,1] # : sign means whole

array([1, 5, 9])

In [15]:
a = np .arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [17]:
b = a.reshape(4,3)   # this reshape command convert distributed array into fixed array shape 
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [18]:
a*2 # * sign multiply the whole array{array * value}

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22])

In [19]:
a**2     # ** means raised to the power 

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121],
      dtype=int32)

In [20]:
a<6 #  < sign show the islessthan and show the boolean value of whole array

array([ True,  True,  True,  True,  True,  True, False, False, False,
       False, False, False])

In [21]:
b*2

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22]])

In [22]:
b>6

array([[False, False, False],
       [False, False, False],
       [False,  True,  True],
       [ True,  True,  True]])

In [3]:
a = np.array((1,2,3))
b = np.array((4,5,6))
print(a)
print(b)

NameError: name 'np' is not defined

In [26]:
b-a    # In this arra a subtracted from array a

array([3, 3, 3])

In [27]:
a*b

array([ 4, 10, 18])

In [2]:
a.dot(b)  # in this dot command all product of array into a single product by add 

NameError: name 'a' is not defined

In [1]:
b.dot(a)

NameError: name 'b' is not defined

In [30]:
a.shape

(3,)

In [31]:
a

array([1, 2, 3])

In [36]:
a.reshape(1,3)

array([[1, 2, 3]])

In [38]:
c = a.reshape(1,3)
c

array([[1, 2, 3]])

In [41]:
d = b.reshape(3,1)
d

array([[4],
       [5],
       [6]])

In [42]:
c.dot(d)     # doubt

array([[32]])

In [43]:
d.dot(c)   #doubt 

array([[ 4,  8, 12],
       [ 5, 10, 15],
       [ 6, 12, 18]])

In [44]:
c.T       # T MEANS TRANSPOSE THE ARRAY

array([[1],
       [2],
       [3]])

In [45]:
d.T

array([[4, 5, 6]])

In [46]:
#  MASKING

In [47]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [48]:
a[a>6] #IN this process filtrate those array elements are greater than 6

array([ 7,  8,  9, 10, 11])

In [50]:
b = np.arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [51]:
b>6

array([[False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True]])

In [53]:
b[b>5]

array([ 6,  7,  8,  9, 10, 11])

In [54]:
a = np.arange(24)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [55]:
a.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [58]:
b = a.reshape(4,6)
b.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [61]:
c = a[:10]
c.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [62]:
b

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [64]:
d = a[a>6]
d.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [65]:
import django

In [66]:
import kivy

[INFO   ] [Logger      ] Record log in C:\Users\Vikas cr\.kivy\logs\kivy_19-04-01_0.txt
[INFO   ] [Kivy        ] v1.10.1
[INFO   ] [Python      ] v3.6.6 (v3.6.6:4cf1f54eb7, Jun 27 2018, 03:37:03) [MSC v.1900 64 bit (AMD64)]


In [67]:
! pip install kivy

In [68]:
import kivy

In [1]:
! pip install pygame

In [2]:
import pygame

pygame 1.9.5
Hello from the pygame community. https://www.pygame.org/contribute.html


In [6]:
import numpy as np

In [7]:
a = np.arange(3)
b = np.array[(1,2,3)]
print(a)
print(b)

TypeError: 'builtin_function_or_method' object is not subscriptable