In [2]:
import numpy as np

In [3]:
a = np.arange(3)


array([0, 1, 2])

In [5]:
b = array[(1,2,3)]
b

NameError: name 'array' is not defined

In [6]:
b  = np.array((1,2,3))
b

array([1, 2, 3])

In [7]:
a.dot(b)
a

array([0, 1, 2])

In [8]:
a.dot(b)

8

In [9]:
b.dot(a)

8

In [1]:
import kivy

[INFO   ] [Logger      ] Record log in C:\Users\Vikas cr\.kivy\logs\kivy_19-04-05_0.txt
[INFO   ] [Kivy        ] v1.10.1
[INFO   ] [Python      ] v3.6.6 (v3.6.6:4cf1f54eb7, Jun 27 2018, 03:37:03) [MSC v.1900 64 bit (AMD64)]


In [2]:
import pygame

pygame 1.9.5
Hello from the pygame community. https://www.pygame.org/contribute.html


In [1]:
! pip install cpython

  Could not find a version that satisfies the requirement cpython (from versions: )
No matching distribution found for cpython


In [2]:
! pip install jpython

  Could not find a version that satisfies the requirement jpython (from versions: )
No matching distribution found for jpython
